return PlaceObj('ModDef', {
	'title', "Community Fix Pack",
	'description', "Fixes bugs in Surviving Mars: Relaunched gameplay code. Every fix targets a verified defect in the game's Lua source, patches at runtime in a mod-compatible way (no game files are modified), and can be individually disabled. See the mod page for the full list of fixes.",
	'id', "SMR_CommunityFixPack",
	'author', "catt144",
	'version', 1,
	'lua_revision', 350453,
	-- Mod Options defaults (D05): must mirror items.lua's ModItemOptionToggle
	-- names, all false. This field is what makes Options → Mod Options list the
	-- pack (ModDef:HasOptions reads it, Mod.lua:473-475), and the engine seeds
	-- CurrentModOptions from it before our code loads.
	'default_options', {
		ClassicRockets = false,
		AcknowledgedWarnings = false,
		ResidencyControl = false,
		MultipleSuns = false,
		DroneOverhaul = false,
		CohortHousing = false,
	},
	'code', {
		"Code/00_Core.lua",
		"Code/Fix_CaveInsNoDisasters.lua",
		"Code/Fix_MeteorFrequency.lua",
		"Code/Fix_UpgradeModifierLeak.lua",
		"Code/Fix_NightShiftWork.lua",
		"Code/Fix_MilestoneCrash.lua",
		"Code/Fix_WispRewards.lua",
		"Code/Fix_TouristApplicants.lua",
		"Code/Fix_TrainsToVoid.lua",
		"Code/Fix_LanderEmptyLaunch.lua",
		"Code/Fix_LanderCargoRatchet.lua",
		"Code/Fix_LanderReturnFuel.lua",
		"Code/Fix_ShelterReflex.lua",
		"Code/Fix_BrokenTrackSalvage.lua",
		"Code/Fix_TrackSalvageWipe.lua",
		"Code/Fix_LakeEntombment.lua",
		"Code/Fix_GhostFarmOxygen.lua",
		"Code/Fix_RocketDroneChurn.lua",
		"Code/Fix_ShuttleTransportCache.lua",
		"Code/Fix_VacuumWalks.lua",
		"Code/Fix_ArrivalDeaths.lua",
		"Code/Fix_DroneUnreachableForever.lua",
		"Code/Fix_StaleReservations.lua",
		"Code/Fix_CrystalMysteryHang.lua",
		"Code/Fix_TouristSatisfaction.lua",
		"Code/Fix_TrainPlatformWedge.lua",
		"Code/Fix_LowStorageWarning.lua",
		"Code/Fix_CommandCenterNumbers.lua",
		"Code/Fix_DomeOverviewHighlight.lua",
		"Code/Fix_TrainCargoDumping.lua",
		"Code/Fix_UniversityOvertraining.lua",
		"Code/Fix_DestroyedTunnels.lua",
		"Code/Fix_DustSicknessBiorobots.lua",
		"Code/Fix_DustSicknessDamage.lua",
		"Code/Fix_GeneForging.lua",
		"Code/Fix_MirrorSphereSite.lua",
		"Code/Fix_PayloadTemplateRefill.lua",
		"Code/Fix_AsteroidLanderAvailable.lua",
		"Code/Fix_ShuttleHubOffAvailable.lua",
		"Code/Fix_FreedHousingNotice.lua",
		"Code/Fix_DomeFreeSpaceMismatch.lua",
		"Code/Fix_SmallLandscapeSites.lua",
		"Code/Fix_LandscapeUnitFilter.lua",
		"Code/Fix_RocketInteractGuard.lua",
		"Code/Fix_TrackConnectorPingPong.lua",
		"Code/Fix_TrackTunnelPowerBridge.lua",
		"Code/Fix_GridGlobalStorage.lua",
		"Code/Fix_LastTransmissionStorage.lua",
		"Code/Fix_GraphConsumedCaption.lua",
		"Code/Fix_MoraleComfortTooltip.lua",
		"Code/Fix_TrainWaitTime.lua",
		"Code/Fix_FounderTraitNotification.lua",
		"Code/Fix_DomePipeMoveInside.lua",
		"Code/Fix_StorageRateModifiers.lua",
		"Code/Fix_ReplaceTechCount.lua",
		"Code/Fix_SequenceLatents.lua",
		"Code/Fix_IndependenceTerraforming.lua",
		"Code/Fix_TrackSalvageRefund.lua",
		"Code/Fix_LayoutTechLock.lua",
		"Code/Fix_TrainMinors.lua",
		"Code/Fix_DroneTransportMinors.lua",
		"Code/Fix_AnomalyCaveInMap.lua",
		"Code/Fix_TechDescriptionBuilding.lua",
		"Code/Fix_BombardmentSpread.lua",
		"Code/Fix_ExtenderFlapChurn.lua",
		"Code/90_SaveSanitizer.lua",
		-- optional modules, off by default (see SMRFixPack_Optional)
		"Code/Opt_ClassicRockets.lua",
		"Code/Opt_AcknowledgedWarnings.lua",
		"Code/Opt_ResidencyControl.lua",
		"Code/Opt_MultipleSuns.lua",
		"Code/Opt_DroneOverhaul.lua",
		"Code/Opt_CohortHousing.lua",
	},
	'TagGameplay', true,
})
