return PlaceObj('ModDef', {
	'title', "Relaunched Fix Pack",
	'description', "Bug fixes for Surviving Mars: Relaunched.\n\nForty-nine repairs, each one written up on the fix list with what you would\nhave seen and what was actually wrong. Every one targets something the game's\nown code gets wrong — the code says one thing, does another, and the fix makes\nit do what it says. It fixes bugs; it does not rebalance the game. Preferences\nand features are deliberately not in it.\n\nSome of them you could hardly miss: an entire train line and every train on it\ndeleted by salvaging a single hex, colonists suffocating on a walk between two\ndomes, an artificial lake burying the rover that was building it.\n\nMore of them you would never have blamed on a bug, because the game looked\nperfectly normal while the arithmetic underneath it was wrong — a reward for\nfreeing the wisps that paid about a thousandth of what its own message promised,\na researched breakthrough the game restored to only one of the three wind\nturbine types it covers, a track refund that paid a stub's worth of Metals\nhowever long the line was, a Comfort penalty billed for longer than the journey\nactually took.\n\nAnd three of them repair things you cannot see at all today: real defects that\nthe shipped numbers happen to hide, which another mod, a game patch or a DLC\ncould walk straight into.\n\n\nSOME OF WHAT IT FIXES\n\n· Colonists walked across the surface between domes and suffocated.\n· Rocket loads of new arrivals died on their way to a dome.\n· New arrivals moved into a dome that was switched off, quarantined or without air.\n· A dome sat half empty and still refused to house anyone.\n· A bed that fell vacant sat empty while colonists were homeless.\n· Night-shift colonists never came back to work after midnight.\n· A salvaged farm kept supplying its dome with oxygen forever.\n· Building an artificial lake buried the rover that built it.\n· Drone Hubs paralysed themselves every time an Extender flickered.\n· Salvaging one piece of track deleted the whole line, and its trains with it.\n· Demolishing a station permanently deleted the trains parked there.\n· Meteor-damaged track could not be salvaged at all.\n· Two train buildings fought over the same connector hex forever.\n· A destroyed tunnel still worked as a shortcut.\n· Automatic rockets and landers took off with nothing aboard.\n· An Earth-sent Trade rocket, most often the Wildfire mystery's cure rocket, could get stuck on the landing pad forever.\n· A Jumbo Cave mystery could get stuck clearing waste rock and never complete.\n· The Philosopher's Stone mystery hung one step from the end.\n· A story step asked for a cave-in on a map that does not exist, and the story stopped.\n· The Gene Forging research did nothing at all.\n· The Domes Overview stopped marking domes in trouble.\n\n… and a good deal more, including quieter repairs to drones, shuttles, domes,\nrockets, research, storylines and the interface.\n\nThe full list — every fix, what you would have seen, and what was actually\nwrong — is here:\nhttps://catt144.github.io/SMR-CommunityMods/fix-list/\n\n\nSEVEN MACHINES THAT WORKED IN SILENCE\n\nThe Rare Metals Extractor's hammer, the MOXIE, the Water Extractor, Shuttle Hub\nshuttles, the RC Driller, the RC Dozer and The Excavator all had sounds or\neffects made for them that never played. They play now.\n\nTwo of them also have a skin that is silent by design, so if one of these stays\nquiet, check its skin before you blame the fix:\n· Rare Metals Extractor — the hammer strikes and puffs steam; the drill never\n  strikes. NASA, SpaceY, BlueSun, Brazil, Roscosmos, Japan and ISRO colonies\n  get the drill by default.\n· MOXIE — the double-pump skin thumps and puffs; the blocky one is silent.\n\nSelect the building and press Change Skin (the paintbrush on its panel) to\nswitch. The screenshots on this page show which skin is which.\n\n\nSTILL PLAYING ON GAME VERSION 1.0.7?\n\nThis pack tracks the current version of the game. If you stayed on 1.0.7, there\nis a separate frozen build for it, with instructions:\nhttps://catt144.github.io/SMR-CommunityMods/legacy-1-0-7/\n\n\nHOW IT WORKS\n\n· No game files are modified. The pack wraps the game's own code while it runs.\n· Safe to add to a save you have already played. It writes almost nothing into\n  your savegame, and removing it simply lets the original bugs come back.\n· Every fix checks the game's code before it touches anything, and stands down\n  by itself if an official patch changes what it was written for. A fix that\n  stands down does nothing at all — it never guesses.\n· A few of the fixes are judgment calls rather than plain repairs. Those are\n  marked as such on the fix list, with the reasoning, rather than folded in\n  quietly.\n\n\nFOUND A BUG, OR ONE THIS PACK DID NOT FIX?\n\nReports are read and acted on, and a save file where it reliably happens is\nworth more than any description of it.\n\n· Issue tracker — the route for everyone, and the only one that can carry a\n  save file or a log:\n  https://github.com/catt144/SMR-CommunityFixPack/issues\n  It needs a free GitHub account and works from a browser on any device.\n\n· If this page has a comment section, that works too for anything you can\n  describe in words. Only the tracker can carry a file.\n\nOn console — every Xbox and PlayStation player — there is nothing to attach in\nthe first place, and a plain description in your own words is genuinely useful.\n\n\nFOR MODDERS\n\nThe pack is built to share the game with your mod rather than take it over. It\nhooks the game's functions and calls the original where it can, so another mod\nthat touches the same function keeps working. Where a bug sits in the middle of\na function and cannot be hooked, the fix copies the corrected body instead —\nthose are the ones most likely to clash, and each one names in its source the\ngame file and lines it came from.\n\nAny single fix can be switched off from another mod, without touching this one.\nSet the fix's id as a key on the veto table before the pack loads:\n\n    SMRFixPack_Disabled = rawget(_G, \"SMRFixPack_Disabled\") or {}\n    SMRFixPack_Disabled[\"LakeEntombment\"] = true\n\nThe id is the key, not a list entry — a plain list looks valid and switches off\nnothing. \"Before the pack loads\" means your mod has to load first.\n\nSource, and the reasoning behind every fix:\nhttps://github.com/catt144/SMR-CommunityFixPack",
	'short_description', "Bug fixes for Surviving Mars: Relaunched — it repairs defects verified in the game's own code rather than rebalancing the game, and it is safe to add to a save you have already played.",
	'image', "Mod/SMR_CommunityFixPack/preview.png",
	'last_changes', "Housing and migration fixes, reviewed against the 1.1.0 patch:\n\n-Freed housing notice — REPAIRED. Assigning a colonist to a residence that was already full could leave that home with more residents than it has beds, and fail to evict the colonist it displaced. That was this pack's own doing, not the game's. The notice now waits until the move that freed the bed has finished. Watched working in a running colony on 1.1.0. The same repair should also stop a colonist boarding an expedition from losing the home held for their return; that half is checked in the code only.\n\n-Dome housing total — RETIRED. 1.1.0 changed how a dome decides whether it has room, and it no longer uses the total this fix corrected. Rather than leave it adjusting a number that no longer feeds the decision, the fix has been removed. The fix list drops from fifty to forty-nine.",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*/Source/*",
		"*/SourceData/*",
		"*/docs/*",
		"*/.claude/*",
		"*/tools/*",
		"*README.md",
		"*CLAUDE.md",
		"*AGENTS.md",
		"*.gitignore",
		"*.gitattributes",
		"*/store_screenshots/*",
	},
	'id', "SMR_CommunityFixPack",
	'author', "catt144",
	'version_major', 1,
	'version', 10,
	'lua_revision', 350453,
	'saved_with_revision', 403908,
	'optional_mod', true,
	'code', {
		"Code/00_Core.lua",
		"Code/Fix_NightShiftWork.lua",
		"Code/Fix_WispRewards.lua",
		"Code/Fix_TrainsToVoid.lua",
		"Code/Fix_LanderEmptyLaunch.lua",
		"Code/Fix_ShelterReflex.lua",
		"Code/Fix_BrokenTrackSalvage.lua",
		"Code/Fix_TrackSalvageWipe.lua",
		"Code/Fix_LakeEntombment.lua",
		"Code/Fix_GhostFarmOxygen.lua",
		"Code/Fix_RocketDroneChurn.lua",
		"Code/Fix_TradeRocketFuelRefresh.lua",
		"Code/Fix_ShuttleTransportCache.lua",
		"Code/Fix_VacuumWalks.lua",
		"Code/Fix_ArrivalDeaths.lua",
		"Code/Fix_StaleReservations.lua",
		"Code/Fix_CrystalMysteryHang.lua",
		"Code/Fix_DomeOverviewHighlight.lua",
		"Code/Fix_TrainCargoDumping.lua",
		"Code/Fix_DestroyedTunnels.lua",
		"Code/Fix_DustSicknessBiorobots.lua",
		"Code/Fix_GeneForging.lua",
		"Code/Fix_MirrorSphereSite.lua",
		"Code/Fix_PayloadTemplateRefill.lua",
		"Code/Fix_ShuttleHubOffAvailable.lua",
		"Code/Fix_FreedHousingNotice.lua",
		"Code/Fix_LandscapeUnitFilter.lua",
		"Code/Fix_RocketInteractGuard.lua",
		"Code/Fix_TrackConnectorPingPong.lua",
		"Code/Fix_TrackTunnelPowerBridge.lua",
		"Code/Fix_GraphConsumedCaption.lua",
		"Code/Fix_TrainWaitTime.lua",
		"Code/Fix_FounderTraitNotification.lua",
		"Code/Fix_SequenceLatents.lua",
		"Code/Fix_TrackSalvageRefund.lua",
		"Code/Fix_LayoutTechLock.lua",
		"Code/Fix_DroneTransportMinors.lua",
		"Code/Fix_AnomalyCaveInMap.lua",
		"Code/Fix_ScanDowngrade.lua",
		"Code/Fix_BombardmentSpread.lua",
		"Code/Fix_ExtenderFlapChurn.lua",
		"Code/Fix_SaintBlessing.lua",
		"Code/Fix_SinkholeIndestructible.lua",
		"Code/Fix_ExoticDepositSign.lua",
		"Code/Fix_JumboCaveReinforcementWedge.lua",
		"Code/Fix_SilentHitMomentFX.lua",
		"Code/90_SaveSanitizer.lua",
	},
	'saved', 1789186283,
	'code_hash', -6221640283017790268,
	'screenshot1', "Mod/SMR_CommunityFixPack/store_screenshots/1_rare_metals_drill_skin.jpg",
	'screenshot2', "Mod/SMR_CommunityFixPack/store_screenshots/2_rare_metals_hammer_skin.jpg",
	'screenshot3', "Mod/SMR_CommunityFixPack/store_screenshots/3_moxie_skins.jpg",
	'pdx_id', 156049,
	'pdx_version', "8",
	'steam_id', "3787202810",
	'TagGameplay', true,
})