return PlaceObj('ModDef', {
	'title', "Community Fix Pack",
	'description', "Fixes bugs in Surviving Mars: Relaunched gameplay code. Every fix targets a verified defect in the game's Lua source and patches at runtime in a mod-compatible way (no game files are modified). The optional modules — six toggles plus Drone speed and carry-capacity dials — are controlled in-game via Mod Options on every platform; individual bug fixes can additionally be disabled on PC (via the console or a companion mod). See the mod page for the full list of fixes.",
	'short_description', "Dozens of verified bug fixes for Surviving Mars: Relaunched, applied at runtime in a mod-compatible way — no game files modified. Plus optional quality-of-life modules — six toggles and two Drone stat dials — all off/at base by default.",
	-- the count below = Fix_*.lua files + 90_SaveSanitizer (66 + 1 as of
	-- 2026-07-30 late). It drifts every time a fix is retired or added — it read
	-- 68 until F24 and F28 were closed `wontfix`, then 66, and F83's
	-- Fix_FirstAsteroidPrefabs brought it to 67. Recount before every release.
	'last_changes', "Initial release: 67 bug fixes, 6 optional modules and Drone speed/carry dials (all in Mod Options).",
	'id', "SMR_CommunityFixPack",
	'author', "catt144",
	'version', 1,
	'version_major', 1,
	'version_minor', 0,
	'lua_revision', 350453,
	-- saves made with the pack load fine without it (FIX_POLICY §3), so don't
	-- nag players who removed it with the missing-mods prompt
	'optional_mod', true,
	-- the packer includes EVERYTHING recursively minus this list (Mod.lua:250-256,
	-- GedModEditor.lua:716-732) — without the extra patterns docs/, README.md,
	-- .gitignore and .claude/ all ship inside the .hpk. LICENSE ships on purpose.
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*/Source/*",
		"*/SourceData/*",
		"*/docs/*",
		"*/.claude/*",
		"*README.md",
		"*.gitignore",
	},
	-- Mod Options defaults (D05): must mirror items.lua's ModItemOptionToggle
	-- names, all false. This field is what makes Options → Mod Options list the
	-- pack (ModDef:HasOptions reads it, Mod.lua:473-475), and the engine seeds
	-- CurrentModOptions from it before our code loads. The two D09 dial
	-- entries are ModItemOptionChoice values — base STRINGS, byte-identical
	-- to items.lua's ChoiceList and Opt_DroneStatDials.lua's maps, not false.
	'default_options', {
		ClassicRockets = false,
		AcknowledgedWarnings = false,
		ResidencyControl = false,
		MultipleSuns = false,
		DroneOverhaul = false,
		CohortHousing = false,
		DroneSpeedDial = "1x (base)",
		DroneCarryDial = "+0 (base)",
	},
	'code', {
		"Code/00_Core.lua",
		"Code/Fix_CaveInsNoDisasters.lua",
		"Code/Fix_MeteorFrequency.lua",
		"Code/Fix_UpgradeModifierLeak.lua",
		"Code/Fix_NightShiftWork.lua",
		"Code/Fix_MilestoneCrash.lua",
		"Code/Fix_WispRewards.lua",
		"Code/Fix_TouristApplicants.lua",
		"Code/Fix_TrainsToVoid.lua",
		"Code/Fix_LanderEmptyLaunch.lua",
		"Code/Fix_LanderCargoRatchet.lua",
		"Code/Fix_LanderReturnFuel.lua",
		"Code/Fix_ShelterReflex.lua",
		"Code/Fix_BrokenTrackSalvage.lua",
		"Code/Fix_TrackSalvageWipe.lua",
		"Code/Fix_LakeEntombment.lua",
		"Code/Fix_GhostFarmOxygen.lua",
		"Code/Fix_RocketDroneChurn.lua",
		"Code/Fix_ShuttleTransportCache.lua",
		"Code/Fix_VacuumWalks.lua",
		"Code/Fix_ArrivalDeaths.lua",
		"Code/Fix_DroneUnreachableForever.lua",
		"Code/Fix_StaleReservations.lua",
		"Code/Fix_CrystalMysteryHang.lua",
		"Code/Fix_TouristSatisfaction.lua",
		"Code/Fix_TrainPlatformWedge.lua",
		"Code/Fix_LowStorageWarning.lua",
		"Code/Fix_CommandCenterNumbers.lua",
		"Code/Fix_DomeOverviewHighlight.lua",
		"Code/Fix_TrainCargoDumping.lua",
		"Code/Fix_UniversityOvertraining.lua",
		"Code/Fix_DestroyedTunnels.lua",
		"Code/Fix_DustSicknessBiorobots.lua",
		"Code/Fix_DustSicknessDamage.lua",
		"Code/Fix_GeneForging.lua",
		"Code/Fix_MirrorSphereSite.lua",
		"Code/Fix_PayloadTemplateRefill.lua",
		"Code/Fix_AsteroidLanderAvailable.lua",
		"Code/Fix_ShuttleHubOffAvailable.lua",
		"Code/Fix_FreedHousingNotice.lua",
		"Code/Fix_DomeFreeSpaceMismatch.lua",
		"Code/Fix_SmallLandscapeSites.lua",
		"Code/Fix_LandscapeUnitFilter.lua",
		"Code/Fix_RocketInteractGuard.lua",
		"Code/Fix_TrackConnectorPingPong.lua",
		"Code/Fix_TrackTunnelPowerBridge.lua",
		"Code/Fix_GridGlobalStorage.lua",
		"Code/Fix_LastTransmissionStorage.lua",
		"Code/Fix_GraphConsumedCaption.lua",
		"Code/Fix_MoraleComfortTooltip.lua",
		"Code/Fix_TrainWaitTime.lua",
		"Code/Fix_FounderTraitNotification.lua",
		"Code/Fix_StorageRateModifiers.lua",
		"Code/Fix_SequenceLatents.lua",
		"Code/Fix_IndependenceTerraforming.lua",
		"Code/Fix_TrackSalvageRefund.lua",
		"Code/Fix_LayoutTechLock.lua",
		"Code/Fix_TrainMinors.lua",
		"Code/Fix_DroneTransportMinors.lua",
		"Code/Fix_AnomalyCaveInMap.lua",
		"Code/Fix_TechDescriptionBuilding.lua",
		"Code/Fix_BombardmentSpread.lua",
		"Code/Fix_ExtenderFlapChurn.lua",
		"Code/Fix_DisasterPredictionLeak.lua",
		"Code/Fix_MeteorStormWedge.lua",
		"Code/Fix_RainsDeadlock.lua",
		"Code/Fix_FirstAsteroidPrefabs.lua",
		"Code/Fix_SaintBlessing.lua",
		"Code/Fix_DustDevilsDescrMap.lua",
		"Code/Fix_AstrogeologistExtractors.lua",
		"Code/Fix_SinkholeIndestructible.lua",
		"Code/90_SaveSanitizer.lua",
		-- optional modules, off by default (see SMRFixPack_Optional)
		"Code/Opt_ClassicRockets.lua",
		"Code/Opt_AcknowledgedWarnings.lua",
		"Code/Opt_ResidencyControl.lua",
		"Code/Opt_MultipleSuns.lua",
		"Code/Opt_DroneOverhaul.lua",
		"Code/Opt_CohortHousing.lua",
		"Code/Opt_DroneStatDials.lua",
	},
	'TagGameplay', true,
})
